/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CheckupsIndexRouteImport } from './routes/checkups.index'
import { Route as CheckupsSlugRouteImport } from './routes/checkups.$slug'
import { Route as ChekapyIndexRouteImport } from './routes/chekapy.index'
import { Route as ChekapySlugRouteImport } from './routes/chekapy.$slug'
import { Route as NapravleniyaIndexRouteImport } from './routes/napravleniya.index'
import { Route as NapravleniyaSlugRouteImport } from './routes/napravleniya.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminCheckupsRouteImport } from './routes/_authenticated/admin/checkups'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin/diagnostics'
import { Route as AuthenticatedAdminDoctorsRouteImport } from './routes/_authenticated/admin/doctors'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin/hero'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminNapravleniyaRouteImport } from './routes/_authenticated/admin/napravleniya'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminPopupsRouteImport } from './routes/_authenticated/admin/popups'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin/seo'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckupsIndexRoute = CheckupsIndexRouteImport.update({
  id: '/checkups/',
  path: '/checkups/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckupsSlugRoute = CheckupsSlugRouteImport.update({
  id: '/checkups/$slug',
  path: '/checkups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChekapyIndexRoute = ChekapyIndexRouteImport.update({
  id: '/chekapy/',
  path: '/chekapy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChekapySlugRoute = ChekapySlugRouteImport.update({
  id: '/chekapy/$slug',
  path: '/chekapy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaIndexRoute = NapravleniyaIndexRouteImport.update({
  id: '/napravleniya/',
  path: '/napravleniya/',
  getParentRoute: () => rootRouteImport,
} as any)
const NapravleniyaSlugRoute = NapravleniyaSlugRouteImport.update({
  id: '/napravleniya/$slug',
  path: '/napravleniya/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckupsRoute =
  AuthenticatedAdminCheckupsRouteImport.update({
    id: '/checkups',
    path: '/checkups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDoctorsRoute =
  AuthenticatedAdminDoctorsRouteImport.update({
    id: '/doctors',
    path: '/doctors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNapravleniyaRoute =
  AuthenticatedAdminNapravleniyaRouteImport.update({
    id: '/napravleniya',
    path: '/napravleniya',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPopupsRoute =
  AuthenticatedAdminPopupsRouteImport.update({
    id: '/popups',
    path: '/popups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/checkups/$slug': typeof CheckupsSlugRoute
  '/chekapy/$slug': typeof ChekapySlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/checkups/': typeof CheckupsIndexRoute
  '/chekapy/': typeof ChekapyIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/checkups': typeof AuthenticatedAdminCheckupsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/napravleniya': typeof AuthenticatedAdminNapravleniyaRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkups/$slug': typeof CheckupsSlugRoute
  '/chekapy/$slug': typeof ChekapySlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/checkups': typeof CheckupsIndexRoute
  '/chekapy': typeof ChekapyIndexRoute
  '/napravleniya': typeof NapravleniyaIndexRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/checkups': typeof AuthenticatedAdminCheckupsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/napravleniya': typeof AuthenticatedAdminNapravleniyaRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/checkups/$slug': typeof CheckupsSlugRoute
  '/chekapy/$slug': typeof ChekapySlugRoute
  '/napravleniya/$slug': typeof NapravleniyaSlugRoute
  '/checkups/': typeof CheckupsIndexRoute
  '/chekapy/': typeof ChekapyIndexRoute
  '/napravleniya/': typeof NapravleniyaIndexRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/checkups': typeof AuthenticatedAdminCheckupsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/doctors': typeof AuthenticatedAdminDoctorsRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/napravleniya': typeof AuthenticatedAdminNapravleniyaRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/popups': typeof AuthenticatedAdminPopupsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/checkups/$slug'
    | '/chekapy/$slug'
    | '/napravleniya/$slug'
    | '/checkups/'
    | '/chekapy/'
    | '/napravleniya/'
    | '/admin/branches'
    | '/admin/checkups'
    | '/admin/content'
    | '/admin/diagnostics'
    | '/admin/doctors'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/napravleniya'
    | '/admin/pages'
    | '/admin/popups'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/sitemap.xml'
    | '/checkups/$slug'
    | '/chekapy/$slug'
    | '/napravleniya/$slug'
    | '/checkups'
    | '/chekapy'
    | '/napravleniya'
    | '/admin/branches'
    | '/admin/checkups'
    | '/admin/content'
    | '/admin/diagnostics'
    | '/admin/doctors'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/napravleniya'
    | '/admin/pages'
    | '/admin/popups'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/checkups/$slug'
    | '/chekapy/$slug'
    | '/napravleniya/$slug'
    | '/checkups/'
    | '/chekapy/'
    | '/napravleniya/'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/checkups'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/doctors'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/napravleniya'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/popups'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckupsSlugRoute: typeof CheckupsSlugRoute
  ChekapySlugRoute: typeof ChekapySlugRoute
  NapravleniyaSlugRoute: typeof NapravleniyaSlugRoute
  CheckupsIndexRoute: typeof CheckupsIndexRoute
  ChekapyIndexRoute: typeof ChekapyIndexRoute
  NapravleniyaIndexRoute: typeof NapravleniyaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkups/': {
      id: '/checkups/'
      path: '/checkups'
      fullPath: '/checkups/'
      preLoaderRoute: typeof CheckupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkups/$slug': {
      id: '/checkups/$slug'
      path: '/checkups/$slug'
      fullPath: '/checkups/$slug'
      preLoaderRoute: typeof CheckupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chekapy/': {
      id: '/chekapy/'
      path: '/chekapy'
      fullPath: '/chekapy/'
      preLoaderRoute: typeof ChekapyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chekapy/$slug': {
      id: '/chekapy/$slug'
      path: '/chekapy/$slug'
      fullPath: '/chekapy/$slug'
      preLoaderRoute: typeof ChekapySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/': {
      id: '/napravleniya/'
      path: '/napravleniya'
      fullPath: '/napravleniya/'
      preLoaderRoute: typeof NapravleniyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/napravleniya/$slug': {
      id: '/napravleniya/$slug'
      path: '/napravleniya/$slug'
      fullPath: '/napravleniya/$slug'
      preLoaderRoute: typeof NapravleniyaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/checkups': {
      id: '/_authenticated/admin/checkups'
      path: '/checkups'
      fullPath: '/admin/checkups'
      preLoaderRoute: typeof AuthenticatedAdminCheckupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/doctors': {
      id: '/_authenticated/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthenticatedAdminDoctorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/napravleniya': {
      id: '/_authenticated/admin/napravleniya'
      path: '/napravleniya'
      fullPath: '/admin/napravleniya'
      preLoaderRoute: typeof AuthenticatedAdminNapravleniyaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/popups': {
      id: '/_authenticated/admin/popups'
      path: '/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AuthenticatedAdminPopupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCheckupsRoute: typeof AuthenticatedAdminCheckupsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminDoctorsRoute: typeof AuthenticatedAdminDoctorsRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNapravleniyaRoute: typeof AuthenticatedAdminNapravleniyaRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPopupsRoute: typeof AuthenticatedAdminPopupsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
    AuthenticatedAdminCheckupsRoute: AuthenticatedAdminCheckupsRoute,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
    AuthenticatedAdminDoctorsRoute: AuthenticatedAdminDoctorsRoute,
    AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminNapravleniyaRoute: AuthenticatedAdminNapravleniyaRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminPopupsRoute: AuthenticatedAdminPopupsRoute,
    AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckupsSlugRoute: CheckupsSlugRoute,
  ChekapySlugRoute: ChekapySlugRoute,
  NapravleniyaSlugRoute: NapravleniyaSlugRoute,
  CheckupsIndexRoute: CheckupsIndexRoute,
  ChekapyIndexRoute: ChekapyIndexRoute,
  NapravleniyaIndexRoute: NapravleniyaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
